"""Phase 3: dump chunks alongside their embedding vectors to a readable .txt.

The gate checks in `src/ingest.py` prove the store is correct numerically. This
produces the artefact you can read to confirm it for yourself -- chunk text, the
metadata a citation is built from, the actual 384-dim vector, and how that
vector relates to every other vector in the index.

Run:
    python -m scripts.dump_embeddings                     # digest, 16 dims shown
    python -m scripts.dump_embeddings --dims 0            # every chunk, all 384 dims
    python -m scripts.dump_embeddings --scheme S3         # one scheme only
    python -m scripts.dump_embeddings --neighbors 5       # top-5 similar per chunk

Writes data/chunks/embeddings_preview.txt (or --out PATH).
Reads the persisted store; never re-embeds unless --reembed is passed.
"""
from __future__ import annotations

import argparse
import datetime
import sys
from typing import List, Optional

import numpy as np

RULE = "=" * 78
THIN = "-" * 78


def format_vector(vector, dims: int, per_line: int = 8) -> str:
    """Render a vector as a wrapped grid of fixed-width numbers."""
    shown = vector if dims in (0, -1) else vector[:dims]
    values = [f"{float(v):+.4f}" for v in shown]
    lines = []
    for start in range(0, len(values), per_line):
        row = values[start : start + per_line]
        label = f"d{start:<3d}"
        lines.append(f"       {label} " + "  ".join(row))
    if dims not in (0, -1) and len(vector) > dims:
        lines.append(f"       ... {len(vector) - dims} more dimensions not shown "
                     f"(use --dims 0 to print all)")
    return "\n".join(lines)


def vector_stats(vector) -> str:
    arr = np.asarray(vector, dtype=np.float32)
    return (
        f"norm={float(np.linalg.norm(arr)):.4f}  "
        f"min={float(arr.min()):+.4f}  "
        f"max={float(arr.max()):+.4f}  "
        f"mean={float(arr.mean()):+.4f}  "
        f"absmax_idx={int(np.argmax(np.abs(arr)))}"
    )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Dump chunks + embeddings to text")
    parser.add_argument("--out", default="data/chunks/embeddings_preview.txt")
    parser.add_argument("--scheme", default=None, help="limit to one scheme id")
    parser.add_argument(
        "--dims",
        type=int,
        default=16,
        help="dimensions to print per chunk; 0 prints all 384",
    )
    parser.add_argument(
        "--neighbors",
        type=int,
        default=3,
        help="nearest-neighbour count per chunk; 0 to skip",
    )
    args = parser.parse_args(argv)

    import chromadb

    from src.config import get_config

    config = get_config()
    client = chromadb.PersistentClient(path=str(config.chroma_dir))
    collection = client.get_collection(config.chroma_collection)

    stored = collection.get(include=["embeddings", "documents", "metadatas"])
    ids = stored["ids"]
    docs = stored["documents"]
    metas = stored["metadatas"]
    vectors = np.asarray(stored["embeddings"], dtype=np.float32)

    print(f"collection : {config.chroma_collection}")
    print(f"path       : {config.chroma_dir}")
    print(f"space      : {collection.metadata}")
    print(f"vectors    : {vectors.shape} {vectors.dtype}")
    print(f"model      : {config.embed_model}")

    if vectors.size == 0:
        print("collection is empty - run `python -m src.ingest` first")
        return 1

    # Cosine similarity == dot product, because the vectors are L2-normalised.
    similarity = vectors @ vectors.T

    # Nearest neighbours, computed over the whole index before any scheme
    # filter, so the neighbour list stays meaningful when --scheme is used.
    neighbours: List[List[int]] = []
    if args.neighbors:
        for i in range(len(ids)):
            order = np.argsort(-similarity[i])
            picked = [j for j in order if j != i][: args.neighbors]
            neighbours.append(picked)

    keep = [
        i
        for i, meta in enumerate(metas)
        if not args.scheme or meta["scheme_id"] == args.scheme.upper()
    ]

    out: List[str] = [
        RULE,
        "EMBEDDING DUMP - chunk text and its vector side by side",
        f"generated by scripts.dump_embeddings.py on "
        f"{datetime.datetime.now().isoformat(timespec='seconds')}",
        RULE,
        f"collection  : {config.chroma_collection}",
        f"path        : {config.chroma_dir}",
        f"space       : cosine (L2-normalised vectors, so cosine == dot product)",
        f"model       : {config.embed_model}",
        f"dimension   : {vectors.shape[1]}",
        f"chunks      : {len(ids)} total, {len(keep)} shown"
        + (f" (scheme {args.scheme.upper()})" if args.scheme else ""),
        f"dims shown  : {'all ' + str(vectors.shape[1]) if args.dims in (0, -1) else str(args.dims)} "
        f"of {vectors.shape[1]}",
        RULE,
        "",
        "Every vector below should have norm=1.0000. If any line does not,",
        "the store was written without normalize_embeddings=True and is wrong.",
        "",
    ]

    for position, i in enumerate(keep, start=1):
        meta = metas[i]
        doc = docs[i]
        out.append(RULE)
        out.append(
            f"[{position}/{len(keep)}] {ids[i]}   section={meta.get('section')!r}"
        )
        out.append(THIN)
        out.append(f"  scheme       : {meta['scheme_id']}  {meta['scheme_name']}")
        out.append(f"  category     : {meta['category']}   plan: {meta['plan']}")
        out.append(f"  source_url   : {meta['source_url']}")
        out.append(f"  last_updated : {meta['last_updated']}   ordinal: {meta['ordinal']}")
        out.append(f"  text length  : {len(doc)} chars, "
                   f"~{len(doc) // 4} tokens")
        out.append(f"  vector       : {vector_stats(vectors[i])}")
        out.append(format_vector(vectors[i], args.dims))
        if args.neighbors:
            out.append("  nearest      :")
            for j in neighbours[i]:
                sim = float(similarity[i][j])
                out.append(
                    f"      {sim:+.4f}  {ids[j]:<10} [{metas[j]['scheme_id']}] "
                    f"{str(metas[j].get('section'))[:40]}"
                )
        out.append("  text         :")
        for line in doc.splitlines():
            out.append(f"      | {line}")
        out.append("")

    out.append(RULE)
    out.append("END OF DUMP")
    out.append(RULE)

    from pathlib import Path

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out), encoding="utf-8")

    shown_dims = vectors.shape[1] if args.dims in (0, -1) else min(args.dims, vectors.shape[1])
    size_mb = out_path.stat().st_size / 1_048_576
    print(f"\nwrote {out_path}")
    print(f"  {len(keep)} chunks x {shown_dims} dims shown, {size_mb:.2f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
