"""Phase 2: build chunks from the cleaned text and write inspectable artifacts.

Run:  python -m scripts.preview_chunks            # reuse data/processed/*.txt
      python -m scripts.preview_chunks --scheme S1

Writes:
  data/chunks/chunks.jsonl        machine-readable, one chunk per line
  data/chunks/chunks_preview.txt  human-readable dump (PRD FR-4)

Reads only from data/processed -- never re-fetches. Re-chunking must never
require network access.
"""
from __future__ import annotations

import datetime
import json
import sys
from collections import Counter
from pathlib import Path
from typing import List, Optional

from src.chunking import Chunk, HeadingAwareStrategy, get_strategy
from src.config import get_config
from src.sources import SCHEMES, SchemeMeta

PREVIEW_RULE = "=" * 78
SEPARATOR = "-" * 78


def fetch_date(config) -> str:
    """Date the source pages were captured, from raw file mtimes."""
    stamps = [p.stat().st_mtime for p in config.raw_dir.glob("*.html")]
    if not stamps:
        return datetime.date.today().isoformat()
    return datetime.date.fromtimestamp(max(stamps)).isoformat()


def load_processed(scheme: SchemeMeta, config) -> Optional[str]:
    path = config.processed_dir / scheme.processed_filename
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8")


def write_jsonl(chunks: List[Chunk], path: Path) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for chunk in chunks:
            handle.write(json.dumps(chunk.to_dict(), ensure_ascii=False) + "\n")


def write_preview(chunks: List[Chunk], path: Path, strategy_name: str) -> None:
    lines: List[str] = [
        PREVIEW_RULE,
        f"CHUNK PREVIEW - strategy={strategy_name}  chunks={len(chunks)}",
        "Generated by scripts/preview_chunks.py from data/processed/*.txt",
        PREVIEW_RULE,
        "",
    ]
    current_scheme = None
    for chunk in chunks:
        if chunk.scheme_id != current_scheme:
            current_scheme = chunk.scheme_id
            lines.append("")
            lines.append(PREVIEW_RULE)
            lines.append(
                f"SCHEME {chunk.scheme_id} - {chunk.scheme_name} "
                f"[{chunk.category} | {chunk.plan}]"
            )
            lines.append(f"URL: {chunk.source_url}")
            lines.append(PREVIEW_RULE)
        lines.append(SEPARATOR)
        lines.append(
            f"{chunk.chunk_id} | section={chunk.section!r} "
            f"| chars={chunk.char_start}-{chunk.char_end} "
            f"| len={len(chunk.text)} | ~tokens={chunk.token_estimate} "
            f"| updated={chunk.last_updated}"
        )
        lines.append(SEPARATOR)
        lines.append(chunk.text)
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: Optional[List[str]] = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    only = None
    if "--scheme" in argv:
        only = argv[argv.index("--scheme") + 1].upper()

    config = get_config()
    config.ensure_dirs()
    last_updated = fetch_date(config)
    strategy = get_strategy("heading_aware")

    print(f"Strategy : {strategy.name}")
    print(f"Sizes    : chunk_size={strategy.chunk_size} "
          f"overlap={strategy.overlap} min_chars={strategy.min_chars}")
    print(f"Excluded : {', '.join(strategy.exclude_sections) or '(none)'}")
    print(f"Updated  : {last_updated}\n")

    all_chunks: List[Chunk] = []
    for scheme in SCHEMES:
        if only and scheme.id != only:
            continue
        text = load_processed(scheme, config)
        if text is None:
            print(f"  [{scheme.id}] MISSING processed text "
                  f"({scheme.processed_filename}) - run fetch_and_clean first")
            continue
        chunks = strategy.split(text, scheme, last_updated)
        all_chunks.extend(chunks)
        sections = len({c.section for c in chunks})
        print(f"  [{scheme.id}] {len(chunks):>4} chunks "
              f"across {sections} sections  ({scheme.name})")

    if not all_chunks:
        print("\nNo chunks produced.")
        return 1

    jsonl_path = config.chunks_dir / "chunks.jsonl"
    preview_path = config.chunks_dir / "chunks_preview.txt"
    if only:
        # Never let a partial run clobber the canonical artifacts: Phase 3
        # ingests chunks.jsonl, and a silent 20-chunk S1-only file would build
        # a broken index that still looks valid.
        jsonl_path = config.chunks_dir / f"chunks_{only}.jsonl"
        preview_path = config.chunks_dir / f"chunks_{only}_preview.txt"
        print(f"\nNOTE: --scheme {only} writes PARTIAL artifacts, not the "
              f"canonical chunks.jsonl")
    write_jsonl(all_chunks, jsonl_path)
    write_preview(all_chunks, preview_path, strategy.name)

    # --- verification report (docs/ChunkingStrategy.md section 8) ---
    lengths = [len(c.text) for c in all_chunks]
    by_section = Counter(c.section for c in all_chunks)
    missing_meta = [
        c.chunk_id
        for c in all_chunks
        if not c.source_url or not c.last_updated or not c.scheme_id
    ]
    over_limit = [c.chunk_id for c in all_chunks if len(c.text) > strategy.chunk_size]
    ids = [c.chunk_id for c in all_chunks]
    duplicate_ids = [k for k, v in Counter(ids).items() if v > 1]

    print("\n" + "=" * 78)
    print(f"total chunks      : {len(all_chunks)}")
    print(f"chars  min/mean/max: {min(lengths)} / "
          f"{sum(lengths)//len(lengths)} / {max(lengths)}")
    print(f"unique chunk_ids  : {len(set(ids))} "
          f"{'(OK)' if not duplicate_ids else f'DUPLICATES: {duplicate_ids}'}")
    print(f"chunks over limit : {len(over_limit)} "
          f"{'(OK)' if not over_limit else over_limit[:5]}")
    print(f"missing citation metadata: {len(missing_meta)} "
          f"{'(OK)' if not missing_meta else missing_meta[:5]}")

    print(f"\n{'section':<52} {'chunks':>6}")
    print("-" * 78)
    for section, count in by_section.most_common():
        print(f"{(section or '(none)')[:50]:<52} {count:>6}")

    if strategy.dropped:
        reasons = Counter(str(d["reason"]) for d in strategy.dropped)
        print(f"\ndropped segments  : {len(strategy.dropped)}")
        for reason, count in reasons.most_common():
            print(f"   {reason:<50} {count:>5}")

    # fact coverage check across all schemes.
    # expected != 5 means the fact is legitimately scheme-specific:
    # only the ELSS scheme carries a lock-in period.
    expected_by_fact = {
        "expense ratio": 5,
        "exit load": 5,
        "min sip": 5,
        "benchmark": 5,
        "riskometer": 5,
        "lock-in": 1,
    }
    print("\nfact coverage (schemes where the fact appears in >=1 chunk):")
    for label, pattern in (
        ("expense ratio", "expense ratio"),
        ("exit load", "exit load"),
        ("min sip", "min. for sip"),
        ("lock-in", "lock-in"),
        ("benchmark", "benchmark"),
        ("riskometer", "riskometer"),
    ):
        hits = {c.scheme_id for c in all_chunks if pattern in c.text.lower()}
        expected = expected_by_fact[label]
        flag = "OK" if len(hits) == expected else f"EXPECTED {expected}"
        print(f"   {label:<14} {len(hits)}/5  {flag}")

    print(f"\nwrote {jsonl_path}")
    print(f"wrote {preview_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
